title: bobbyxdevel
email: contact@bobbyxdev.xyz
description: >- # this means to ignore newlines until "baseurl:"
  The personal website and blog of bobbyxdevel.
author: bobbyxdevel
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bobbyxdevel-gh.github.io/bobbyx-de/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  bobbyxdevel-gh